problem_title = "Even Fibonacci numbers"
problem_statement = (
    "Each new term in the Fibonacci sequence is generated by adding the previous two terms. "
    "By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... "
    "By considering the terms in the Fibonacci sequence whose values do not exceed four million, "
    "find the sum of the even-valued terms."
)


def solve(num=4000000):
    first_val = 1
    second_val = 1
    total = 0

    while first_val + second_val < num:
        new_val = first_val + second_val
        if new_val % 2 == 0:
            total += new_val
        first_val = second_val
        second_val = new_val

    return total
